baseURL = "/"
locale = "zh-CN"
title = "SHAIFX的技术博客"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  comments = true

  [params.homeInfoParams]
    Title = "SHAIFX 👋"
    Content = "> 写代码、做游戏、搞AI、拥抱开源。\n>\n> 折腾是目的，开源是态度。"

  [params.giscus]
    repo = "0xshai/myblog"
    repoId = "R_kgDOSjif3g"
    category = "Announcements"
    categoryId = "DIC_kwDOSjif3s4C9qHd"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "zh-CN"

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    name = "书签"
    url = "/bookmark/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]